- [Dconf Editor](https://apps.gnome.org/DconfEditor/) is a tool to allow direct editing of the dconf configuration database.
- [dconf-editor](https://gitlab.gnome.org/GNOME/dconf-editor) repo
- @@html: <img src="https://apps.gnome.org/assets/screenshots/ca.desrt.dconf-editor/screenshot1.png" alt="Dconf Editor" class="invert" />@@